# create different model combinations

create_combinations <- function(){
  
  combinations <- list(list(name = "fluA",
                            p_inf = 0.0972,
                            inc_period = 2,
                            inf_period = 5,
                            imm_period = 360, 
                            imm_sd = 0.3,
                            lb = c(rep(0, 5), rep(0, 5), 180, -3),
                            ub = c(rep(1, 5), rep(1, 5), 545, 3)), 
                       list(name = "fluB",
                            p_inf = 0.0972,
                            inc_period = 2,
                            inf_period = 6,
                            imm_period = 360,
                            imm_sd = 0.3,
                            lb = c(rep(0, 5), rep(0, 5), 180, -3),
                            ub = c(rep(1, 5), rep(1, 5), 545, 3)),
                       list(name = "RSV",
                            p_inf = 0.0972,
                            inc_period = 4.98,
                            inf_period = 6.16,
                            imm_period = 358.9,
                            imm_sd = 0.3,
                            lb = c(rep(0, 5), rep(0, 5), 180, -3),
                            ub = c(rep(1, 5), rep(1, 5), 545, 3)), 
                       list(name = "hCOV",
                            p_inf = 0.0972,
                            inc_period = 3,
                            inf_period = 3.5,
                            imm_period = 360,
                            imm_sd = 0.3,
                            lb = c(rep(0, 5), rep(0, 5), 180, -3),
                            ub = c(rep(1, 5), rep(1, 5), 545, 3)), 
                       list(name = "AdV",
                            p_inf = 0.0972,
                            inc_period = 6,
                            inf_period = 5.5,
                            imm_period = 360,
                            imm_sd = 0.3,
                            lb = c(rep(0, 5), rep(0, 5), 30, -3),
                            ub = c(rep(1, 5), rep(1, 5), 365, 3)), 
                       list(name = "RV",
                            p_inf = 0.0972,
                            inc_period = 2,
                            inf_period = 11,
                            imm_period = 360,
                            imm_sd = 0.3,
                            lb = c(rep(0, 5), rep(0, 5), 14, -3),
                            ub = c(rep(1, 5), rep(1, 5), 365, 3)), 
                       list(name = "hMPV",
                            p_inf = 0.0972,
                            inc_period = 4,
                            inf_period = 10.5,
                            imm_period = 360,
                            imm_sd = 0.3,
                            lb = c(rep(0, 5), rep(0, 5), 180, -3),
                            ub = c(rep(1, 5), rep(1, 5), 545, 3)),
                       list(name = "PIV",
                            p_inf = 0.0972,
                            inc_period = 2.6,
                            inf_period = 10,
                            imm_period = 360,
                            imm_sd = 0.3,
                            lb = c(rep(0, 5), rep(0, 5), 30, -3),
                            ub = c(rep(1, 5), rep(1, 5), 365, 3)))
                       
  return(combinations)
  
}
