# Model fitting using Rcpp C++ ODE solver ----
# Drop-in replacement for fit_model.r; sources model_rcpp.r instead of model.r.
# Assumes library_and_scripts.r, explore_contacts.r (for fortnight_matrix /
# fortnight_lookup), and explore_scotland.r (for scot_population, scot_births,
# daily_births, hazard_death, tot1-tot9) have already been sourced.

# need scot_population and scot_births loaded from R/explore_scotland.r
source(here("R", "model_rcpp.r"))

# ---- fit window ----
# Single lever controlling how much of the time series is fitted.
# Change fit_end to shorten/extend; everything below is derived from it.
fit_start <- as.Date("2020-03-23")
fit_end   <- as.Date("2022-03-02")   # <- fit only up to 2 January 2022 (original is 2 March 2022)
# override the default `times <- seq(0, 709, by = 1)` from model_rcpp.r
times <- seq(0, as.integer(fit_end - fit_start), by = 1)

# need fortnight_matrix generated by explore_contacts.r (line 142-252)
# Pre-flatten contact matrices once (expensive step done outside MCMC loop)
contacts_prepped <- prepare_contacts_cpp(fortnight_matrix, fortnight_lookup)

# ---- helper data ----

pathogen_map <- c(
  fluA = "Influenza A",
  fluB = "Influenza B",
  RSV  = "RSV",
  hCOV = "Seasonal coronavirus",
  AdV  = "Adenovirus",
  RV   = "Rhinovirus",
  hMPV = "HMPV",
  PIV  = "Parainfluenza (Any Type)"
)

data <- read_csv("inst/data/cases_all_respiratory_pathogens_by_agegroup_sex_20251008.csv") %>%
  filter(Sex == "Total",
         !AgeGroup %in% c("Total", "Unknown"),
         !Pathogen %in% c("Influenza (All)", "COVID-19", "Mycoplasma pneumoniae")) %>%
  mutate(WeekBeginning = as.Date(as.character(WeekBeginning), format = "%Y%m%d")) %>%
  # filter(WeekBeginning >= as.Date("2020-03-23"),
  #        WeekBeginning <= as.Date("2022-03-02")) %>%
  filter(WeekBeginning >= fit_start,
         WeekBeginning <= fit_end) %>%
  pivot_wider(names_from = AgeGroup, values_from = NumberCasesPerWeek) %>%
  mutate(`0 to 4` = `<1` + `1 to 4`,
         `65+` = `65 to 74` + `75+`) %>%
  select(-c(`<1`, `1 to 4`, `65 to 74`, `75+`)) %>%
  arrange(WeekBeginning) %>%
  select(Pathogen, "0 to 4", "5 to 14", "15 to 44", "45 to 64", "65+")

# dates_seq <- seq.Date(as.Date("2020-03-23"), as.Date("2022-03-02"), by = 1)
dates_seq <- seq.Date(fit_start, fit_end, by = 1)
week_start <- floor_date(dates_seq, unit = "week", week_start = 1)
# pre-coerced grouping for rowsum(): avoids re-coercing Dates on every likelihood call.
# character (not factor) so the rownames stay date strings for downstream as.Date()
week_group <- as.character(week_start)

tots <- c(tot1, tot2, tot3, tot4, tot5, tot6, tot7, tot8, tot9)

# indexing for parameters (to keep better track)
idx <- list(det = 1:5, sus = 6:10, imm = 11, imp = 12)
band_of_group <- c(1, 2, 2, 3, 3, 3, 4, 4, 5)   # 9 model groups -> 5 data bands
u_idx <- c(idx$det, idx$sus, idx$imp)

# incidence column positions in seirs_rcpp() output: time + 4 states x n_age, then inc1..inc9
n_age_model <- 9
inc_cols <- 1 + 4 * n_age_model + seq_len(n_age_model)

# ---- C++-backed model runner ----

# Identical interface to run_model() in fit_model.r, but uses the Rcpp ODE solver.
# Returns a matrix of weekly incidence counts (rows = weeks, cols = 5 age bands).
run_model_rcpp <- function(p_sus_bands, n, imm_days, imports = 1) {
  sigma <- 1 / combinations[[n]]$inc_period
  gamma <- 1 / combinations[[n]]$inf_period
  bg    <- imports / sum(tots)
  
  R_init <- tots * (1 - p_sus_bands[band_of_group])
  S_init <- tots - R_init
  E_init <- bg * S_init / sigma         
  I_init <- bg * S_init / gamma
  
  y0_mat <- rbind(S = S_init - E_init - I_init,
                  E = E_init,
                  I = I_init,
                  R = R_init)
  y0 <- setNames(as.vector(y0_mat),
                 paste0(rep(c("S", "E", "I", "R"), 9), rep(1:9, each = 4)))
  
  out <- seirs_rcpp(
    y0 = y0,
    times = times,
    parms = list(
      sigma = sigma,
      gamma = gamma,
      omega = 1 / imm_days,
      p_inf = combinations[[n]]$p_inf,
      bg    = bg,
      mu_b  = daily_births,
      mu_d  = hazard_death
    ),
    contacts_prepped = contacts_prepped
  )

  daily_inc <- out[, inc_cols, drop = FALSE]   # inc_cols precomputed at module level

  # Aggregate age groups to match observed data (same as fit_model.r)
  daily_agg <- cbind(
    daily_inc[, 1],                                             # 0-4
    daily_inc[, 2] + daily_inc[, 3],                            # 5-14
    daily_inc[, 4] + daily_inc[, 5] + daily_inc[, 6],           # 15-44
    daily_inc[, 7] + daily_inc[, 8],                            # 45-64
    daily_inc[, 9]                                              # 65+
  )

  rowsum(daily_agg, week_group)
}

# ---- MCMC fitting ----

# settings <- list(iterations = 500000, burnin = 200000, nrChains = 1)
settings <- list(iterations = 5000, burnin = 0, nrChains = 1)

results <- list()

for (n in seq_along(combinations)) {
  virus_name <- combinations[[n]]$name
  pathogen_name <- pathogen_map[[virus_name]]
  cat("Fitting combination", n, ":", virus_name)

  subdata <- data %>% filter(Pathogen == pathogen_name)

  local({
    n_local <- n
    data_local <- subdata
    # observed counts flattened once: this was rebuilt from the tibble on every
    # likelihood call, which is ~500k identical tibble subsets + matrix coercions
    obs_vec <- as.vector(as.matrix(subdata[, -1]))

    # prior_local <- createUniformPrior(
    #   lower = combinations[[n_local]]$lb,
    #   upper = combinations[[n_local]]$ub
    # )

    lb <- combinations[[n_local]]$lb
    ub <- combinations[[n_local]]$ub
    # prior median = imm_period; tune sdlog as needed
    imm_meanlog <- log(combinations[[n_local]]$imm_period)
    imm_sdlog <- combinations[[n_local]]$imm_sd

    prior_local <- createPrior(
      density = function(param) {
        ld_uniform <- sum(dunif(param[u_idx], min = lb[u_idx], max = ub[u_idx], log = TRUE))
        ld_imm <- dlnorm(param[idx$imm],
                         meanlog = imm_meanlog, sdlog = imm_sdlog,
                         log = TRUE)
        ld_uniform + ld_imm
      },
      sampler = function(n = 1) {
        u <- mapply(function(lo, hi) runif(n, lo, hi), lb[u_idx], ub[u_idx])
        d <- rlnorm(n, meanlog = imm_meanlog, sdlog = imm_sdlog)
        if (n == 1) c(u[1:10], d, u[11]) else cbind(u[, 1:10], d, u[, 11])
        },
      lower = c(lb[1:10], 0,   lb[12]),
      upper = c(ub[1:10], Inf, ub[12])
    )

    likelihood <- function(param) {
      detection_rates <- param[idx$det]
      p_sus_bands     <- param[idx$sus]
      imm_duration    <- param[idx$imm]
      imports         <- 10^param[idx$imp]

      model_out <- run_model_rcpp(p_sus_bands, n_local, imm_duration, imports)

      # equivalent to as.vector(sweep(model_out, 2, detection_rates, `*`)) but skips
      # sweep's array machinery; as.vector() is column-major, matching rep(each = nweeks)
      expected_vec <- as.vector(model_out) *
        rep(detection_rates, each = nrow(model_out))

      ll <- sum(dpois(obs_vec, expected_vec, log = TRUE))
      if (!is.finite(ll)) return(-1e10)
      ll
    }

    setup <- createBayesianSetup(
      likelihood = likelihood,
      prior = prior_local,
      parallel = FALSE,
      names = c(paste0("detection_", c("0to4","5to14","15to44","45to64","65plus")),
                paste0("sus_",       c("0to4","5to14","15to44","45to64","65plus")),
                "imm_duration", "log10_import")
    )

    set.seed(24)
    chains <- mclapply(1:4,
                       function(x) {
                         runMCMC(bayesianSetup = setup, sampler = "DEzs", settings = settings)
                       },
                       mc.cores = 4)
    out <- createMcmcSamplerList(chains)

    results[[virus_name]] <<- out
  })

  cat(" Done:", virus_name, "\n")
}

saveRDS(results, file = here("inst", "outdata", "parameters_rcpp_sus_det_imm_03082026"))

# ---- manual diagnostic checks ----
summary(results[["RSV"]])
getSample(results[["RSV"]], start = 3)
plot(results[[3]], start = 2)
correlationPlot(results[["RSV"]])

# ---- run with posterior samples ----

results_traj <- list()

for (n in seq_along(combinations)) {
  virus_name <- combinations[[n]]$name
  pathogen_name <- pathogen_map[[virus_name]]
  cat("Trajectory", n, ":", virus_name)

  local({
    n_local <- n
    posterior <- getSample(results[[n_local]], start = 3, thin = 100)

    traj <- lapply(seq_len(nrow(posterior)), function(r) {
      detection_rates <- posterior[r, idx$det]
      p_sus_bands     <- posterior[r, idx$sus]
      imm_duration    <- posterior[r, idx$imm]
      imports         <- 10^posterior[r, idx$imp]

      model_out <- run_model_rcpp(p_sus_bands, n_local, imm_duration, imports)
      expected_out <- sweep(model_out, 2, detection_rates, `*`)
      colnames(expected_out) <- c("0 to 4", "5 to 14", "15 to 44", "45 to 64", "65+")
      expected_out
    })

    results_traj[[virus_name]] <<- traj
  })

  cat("  Done:", virus_name, "\n")
}

saveRDS(results_traj, file = here("inst", "outdata", "traj_rcpp_sus_det_imm_03082026"))

# ---- process trajectories for plotting ----

n <- 6
virus_name <- combinations[[n]]$name
pathogen_name <- pathogen_map[[virus_name]]

traj <- results_traj[[virus_name]]
obs_data <- data %>% filter(Pathogen == pathogen_name)

# traj is a list of weekly-incidence matrices (rows=weeks, cols=5 age bands)
# summarise across posterior samples
week_dates <- as.Date(rownames(traj[[1]]))  # dates from rownames set by rowsum

traj_mat <- do.call(cbind, lapply(traj, function(m) rowSums(m)))  # total across age groups

traj_hdi <- traj_mat %>%
  t() %>%
  hdi() %>%
  rbind(mean = colMeans(t(traj_mat))) %>%
  t() %>%
  as.data.frame() %>%
  mutate(date = week_dates)

# ---- Rt calculation (reused from fit_model.r, compatible with seirs_rcpp output) ----
### date data frame for assistance/reference
# dates <- data.frame(date = seq(as.Date("23-03-2020", format = "%d-%m-%Y"), as.Date("02-03-2022", format = "%d-%m-%Y"), 1)) %>%
dates <- data.frame(date = seq(fit_start, fit_end, 1)) %>%
  mutate(time = 0:(n()-1),
         fortnight = paste(isoyear(date), "/", sprintf("%02d", ceiling(isoweek(date)/2))),
         mmyyyy = format(date, "%m/%Y"),
         quarter = quarters(date)) %>% 
  mutate(fortnight_n = as.integer(factor(fortnight)))

calculate_rt <- function(ode_out, p_inf, gamma, dates_df = dates) {
  t_vec <- ode_out[, "time"]

  rt_vec <- vapply(seq_along(t_vec), function(i) {
    t <- t_vec[i]

    S <- ode_out[i, seq(2, 34, by = 4)]
    E <- ode_out[i, seq(3, 35, by = 4)]
    I <- ode_out[i, seq(4, 36, by = 4)]
    R <- ode_out[i, seq(5, 37, by = 4)]
    N <- S + E + I + R

    C <- c_t(t)

    K <- outer(1:9, 1:9, function(i_id, j_id) {
      C[cbind(i_id, j_id)] * p_inf * S[i_id] / (N[j_id] * gamma)
    })

    Re(eigen(K, only.values = TRUE)$values[1])
  }, numeric(1))

  data.frame(time = t_vec, rt = rt_vec) %>%
    left_join(dates_df, by = "time")
}

results_rt <- list()

for (n in seq_along(combinations)) {
  virus_name <- combinations[[n]]$name
  pathogen_name <- pathogen_map[[virus_name]]
  cat("Rt trajectory", n, ":", virus_name)

  local({
    n_local <- n
    posterior <- getSample(results[[n_local]], start = 2, thin = 100)

    rt_traj <- lapply(seq_len(nrow(posterior)), function(r) {
      p_sus_bands  <- posterior[r, idx$sus]
      imm_duration <- posterior[r, idx$imm]
      imports      <- 10^posterior[r, idx$imp]
      
      sigma <- 1 / combinations[[n_local]]$inc_period
      gamma <- 1 / combinations[[n_local]]$inf_period
      bg    <- imports / sum(tots)
      
      R_init <- tots * (1 - p_sus_bands[band_of_group])
      S_init <- tots - R_init
      E_init <- bg * S_init / sigma
      I_init <- bg * S_init / gamma
      
      y0_mat <- rbind(S = S_init - E_init - I_init, E = E_init,
                      I = I_init, R = R_init)
      y0 <- setNames(as.vector(y0_mat),
                     paste0(rep(c("S", "E", "I", "R"), 9), rep(1:9, each = 4)))

      ode_out <- seirs_rcpp(
        y0  = y0,
        times = times,
        parms = list(
          sigma = 1 / combinations[[n_local]]$inc_period,
          gamma = 1 / combinations[[n_local]]$inf_period,
          omega = 1 / imm_duration,
          p_inf = combinations[[n_local]]$p_inf,
          bg = bg,
          mu_b = daily_births,
          mu_d = hazard_death
        ),
        contacts_prepped = contacts_prepped
      )

      calculate_rt(ode_out,
                   p_inf = combinations[[n_local]]$p_inf,
                   gamma = 1 / combinations[[n_local]]$inf_period)
    })

    results_rt[[virus_name]] <<- rt_traj
  })

  cat("  Done:", virus_name, "\n")
}

saveRDS(results_rt, file = here("inst", "outdata", "rt_rcpp_sus_det_imm_13072026"))
